### ISSUE TITLE
Should pings be rows or columns?

### ISSUE THREAD

**Issue by RobBlackwell** [rolandproud/pyechomask#4]
We need to think carefully about row, column order in Sv matrices.

If pings are columns then this is convenient for echograms.

If pings are rows then it makes it much easier to manipulate file and data structures - pings can easily be appended to a file or memory buffer. Files can be indexed by pings being an offset into the file etc. It's easier to support stream processing architectures etc

My preference is for rows to be pings, but that does imply a matrix transpose to display an echogram in matplotlib.

**Comment by rolandproud** [comment]
This is interesting. I'm inclined to agree. This will be unfamiliar to most users though. I will have a think about it more.
