### ISSUE TITLE
Consider moving plotting to a separate library

### ISSUE THREAD

**Issue by RobBlackwell** [rolandproud/pyechomask#6]
I think plotting and visualisation is orthogonal to the business of masks and warrants its own separate library.

E.g.

I might want to use some different kind of visualisation (alternatives to matplotlib exist)

If I'm using this code on an autonomous vehicle, I might not be interested in visualisation at all.

**Comment by rolandproud** [comment]
Yep i agree, perhaps pyechoplot - will look into it.
